mini program/C/FlaskPrject/FlaskProject/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from FlaskProject.extension import init_ext
from FlaskProject.setting import envs
from FlaskProject.views import init_blue


def create_app(env):
    app = Flask(__name__)

    # 初始化配置
    app.config.from_object(envs.get(env))

    # 初始化扩展库
    init_ext(app=app)

    # 初始化路由
    init_blue(app=app)

    # 初始化Bootstrap
    bootstrap = Bootstrap(app)

    return app

mini program/C/FlaskPrject/FlaskProject/views/__init__.py
from FlaskProject.views.index_view import index_blue
from FlaskProject.views.resume_view import resume_blue
from FlaskProject.views.travel_log_view import travel_log_blue


def init_blue(app):
    app.register_blueprint(blueprint=index_blue)
    app.register_blueprint(blueprint=resume_blue)
    app.register_blueprint(blueprint=travel_log_blue)

mini program/C/FlaskPrject/FlaskProject/views/index_view.py
from flask import Blueprint, render_template

index_blue = Blueprint("index_blue", __name__, url_prefix="/")


@index_blue.route("/")
def index():
    return render_template('index.html', index=index)

mini program/C/FlaskPrject/FlaskProject/views/resume_view.py
from flask import Blueprint, render_template

resume_blue = Blueprint("resume_blue", __name__, url_prefix="/resume")


@resume_blue.route("/")
def resume():
    return render_template('resume.html')

mini program/C/FlaskPrject/FlaskProject/views/travel_log_view.py
from flask import Blueprint, render_template

travel_log_blue = Blueprint("travel_log_blue", __name__, url_prefix="/travel_log")


@travel_log_blue.route("/")
def travel_log():
    return render_template('travel_log.html')

mini program/C/FlaskPrject/FlaskProject/templates/index.html
{% extends "bootstrap/base.html" %}
{% block title %}首页{% endblock %}
{% block header_extends %}{% endblock %}
{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for("index_blue.index") }}">首页</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for("resume_blue.resume") }}">简历</a></li>
                    <li><a href="{{ url_for("travel_log_blue.travel_log") }}">旅行</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1 align="center" style="height: 50px">欢迎查阅</h1>
        </div>
        <table width="600" align="center">
            <tr>
                <td><h3>注：做的题目为Zingfront智线笔试题2018版C新</h3></td>
            </tr>
            <tr>
                <td>
                    <a href="https://github.com/Mr-xiuxing/Trivial/blob/master/mini%20program/str_search.py"><h3>
                        题1、寻找公共单词</h3></a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="https://github.com/Mr-xiuxing/Trivial/blob/master/mini%20program/resolve.py"><h3>
                        题2、将整数能分解成若干个连续整数的和的形式</h3></a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{{ url_for("resume_blue.resume") }}"><h3>题3、个人简历HTML版</h3></a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{{ url_for("travel_log_blue.travel_log") }}"><h3>题4、旅行日志</h3></a>
                </td>
            </tr>
        </table>
    </div>

{% endblock %}

mini program/C/FlaskPrject/FlaskProject/templates/resume.html
{% extends 'index.html' %}
{% block title %}个人简历{% endblock %}
{% block content %}
<div>
    <table width="800" align="center">
        <tr>
            <h1 align="center">Python开发工程师</h1>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td><b>个人信息</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>&emsp;&emsp;姓名：张文豪</td>
            <td width="200" height="30"></td>
            <td>手机：15020189515</td>
            <td width="100" height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;学历：本科</td>
            <td width="200" height="30"></td>
            <td>邮箱：15020189515@163.com</td>
            <td width="100" height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;专业：计算机科学技术</td>
            <td width="200" height="30"></td>
            <td>经验：3年</td>
            <td width="100" height="30"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td><b>求职意向</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>&emsp;&emsp;工作性质：全职</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;应聘职位：Python工程师</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;目前状况：离职状态，可立即上岗</td>
            <td height="30"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td><b>专业技能</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>&emsp;&emsp;熟练运用Python语言，熟悉Python标准库和流行的第三方库</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉OOP面向对象编程，以及AOP面向切面编程</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟练使用web开发框架Django以及Flask</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉MTV/MVC/装饰器设计模式，熟悉ORM框架</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉RESTful设计风格，熟悉Django-REST-framework实现前后端分离开发</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉HTML、CSS以及Bootstrap，了解JavaScript、JQuery等前端技术</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟练XPath、BeautifulSoup、RE网页源代码解析工具，及fiddler抓包工具</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟练使用爬虫框架Scrapy，以及urllib、urllib2以及requests等网络模块</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉常见的反爬虫与反反爬虫策略</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉MySQL、SQLite关系型数据库，熟练使用基本SQL语句</td>
            <td height="30"></td>
        <tr>
            <td>&emsp;&emsp;熟悉Redis以及MongoDB非关系型数据库</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;熟悉Linux常用命令以及Ubuntu开发环境，可熟练在Linux环境下开发</td>
            <td height="30"></td>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td><b>工作经历</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">

    <table align="center" width="800">
        <tr>
            <td>2015/9-2016/10</td>
            <td width="100" height="30"></td>
            <td>乐视网（上海）信息技术有限公司</td>
            <td width="100" height="30"></td>
            <td>Python工程师</td>
            <td width="100" height="30"></td>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;1.参与需求分析，产品设计及上线项目的功能拓展、迭代开发的部分任务</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;2.负责公司产品后端技术开发与维护，接受来自产品的挑战</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;3.对所开发的功能进行测试并建立和完善开发文档</td>
        </tr>
    </table>
    <table align="center" width="800">
        <tr>
            <td>2016/11-2019/2</td>
            <td width="100" height="30"></td>
            <td>上海炫体信息科技有限公司</td>
            <td width="100" height="30"></td>
            <td>Python开发工程师</td>
            <td width="100" height="30"></td>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;1.负责与前端开发人员协调定制API文档</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;2.配合团队其他成员进行模块开发及整合</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;3.负责系统平台的日常维护，对已完成项目的迭代开发，功能拓展</td>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td><b>项目经验</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>&emsp;&emsp;<b>雷速体育社区（已上线）</b></td>
            <td height="50"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目描述：</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;雷速体育社区是一个综合性的体育交流平台，为用户提供在喜欢的体育板块发帖、上传图片、点赞、评论等功能</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目职责:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.与前端人员协调定制API接口</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.负责后端部分业务逻辑代码实现</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.社区热门讨论的展示</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4.发帖、上传图片、点赞、评论等功能的实现</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;5.负责后期维护，以及版本迭代</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>技术要点:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.使用DRF快速高效的实现API接口开发</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.基于DRF的PageNumberPagination重写分页功能</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.使用Redis来完成Django的缓存框架</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4.利用IsAuthenticated判断用户是否登录</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;5.采用了基于ckeditor的富文本编辑器实现社区发帖等功能</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;6.采用七牛云存储用户上传的图片</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>雷速体育情报中心（已上线）</b></td>
            <td height="50"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目描述：</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;情报中心旨在及时的将体育相关的情报分析、转换会帅、伤病处罚等信息咨询及时的展现给用户。</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目职责:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.和产品确认需求</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.与项目组讨论架构选型</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.与前端协商定制接口</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>技术要点:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.使实用Django ORM搭建数据模型</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.使用RESTAPI实现前后分离</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.使用IsAdminUser判断用户是否是管理员</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4.使用Django-Xadmin替换admin</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;5.通过AOP中间件定制反爬机制</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>乐视商城app(运营中)</b></td>
            <td height="50"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目描述：</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;乐视商城是乐视旗下，基于“平台+内容+终端+应用”垂直整合乐视生态，打造的全球生态型电商平台。</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目职责:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.负责登录注册模块以及部分前端页面的编写</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.用户个人中心信息的更改，如密码、邮箱的修改</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.商品页面的分类，轮播图，及详情显示</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>技术要点:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.使用Django REST framework实现前后端分离开发</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.在Serializer类中重写create方法，用户注册密码加密</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.邮箱使用token激活验证方式</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4.前端使用Bootstrap + Swiper 框架搭建</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>体育资讯获取系统</b></td>
            <td height="50"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目描述：</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;对腾讯、网易等门户网站体育板块进行相关资讯提取，并持久化存储</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>项目职责:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.分析网页结构的逻辑结构，制定爬取方案</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.按需求对网页内容进行爬取</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.清洗采集数据，进行持久化存储</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;<b>技术要点:</b></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;1.使用Scrapy框架，搭建</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;2.使用XPath提取页面结构化数据</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;3.编写随机UA及运用ip代理池，防止ip被封</td>
        </tr>
        <tr>
            <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;4.数据持久化至MongoDB</td>
        </tr>
    </table>
    <table width="800" align="center">
        <tr>
            <td><b>教育经历</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>2011/9-2015/7</td>
            <td width="100" height="30"></td>
            <td>泰山学院</td>
            <td width="100" height="30"></td>
            <td>计算机科学与技术</td>
            <td width="100" height="30"></td>
            <td>本科</td>
            <td width="100" height="30"></td>
        </tr>
    </table>
    <table align="center" width="800">
        <tr>
            <td><b>个人评价</b></td>
            <td height="50"></td>
        </tr>
    </table>
    <hr width="800" align="center">
    <table align="center" width="800">
        <tr>
            <td>&emsp;&emsp;1.热爱编程，有良好的沟通能力和团队协作能力</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;2.积极乐观，拥有较强的抗压能力</td>
            <td height="30"></td>
        </tr>
        <tr>
            <td>&emsp;&emsp;3.有较强的学习能力，乐于学习新知识</td>
            <td height="30"></td>
        </tr>
    </table>
</div>
{% endblock %}

mini program/C/FlaskPrject/FlaskProject/templates/travel_log.html
<html lang="en">
<head>
    <title>旅行日志</title>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=IDvNBsejl9oqMbPF316iKsXR"></script>
    <script type="text/javascript"
            src="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.js"></script>
    <link rel="stylesheet" href="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.css"/>
</head>
<body>
<div class="demo_main">
    <fieldset class="demo_content">
        <div style="min-height: 100%; width: 100%;" id="map">
        </div>
        <script type="text/javascript">
            var markerArr = [
                {title: "名称：故宫", point: "116.403414,39.924091", address: "北京市东城区景山前街4号", details: "想去还没去的地方"},
                {title: "名称：泰山学院", point: "117.045912,36.22822", address: "泰安市岱岳区东岳大街525号", details: "成长的地方"},
                {title: "名称：泰山", point: "117.09873,36.269575", address: "泰安市岱岳区东岳大街西段501号", details: "会当凌绝顶，一览众山小"},
                {title: "名称：大明湖公园", point: "117.03246,36.680728", address: "大明湖路271号 ", details: "大明湖畔没有皇上，也没有夏雨荷"},
                {title: "名称：千佛山", point: "117.04269,36.645042", address: "经十一路18号 ", details: "千佛山风景名胜区"},
                {title: "名称：东方明珠", point: "121.506377,31.245105", address: "上海市浦东新区世纪大道1号", details: "曾经工作的地方"}
            ];

            function map_init() {
                var map = new BMap.Map("map"); // 创建Map实例
                var point = new BMap.Point(116.403326, 39.915351); //地图中心点，北京
                map.centerAndZoom(point, 6); // 初始化地图,设置中心点坐标和地图级别。
                map.enableScrollWheelZoom(true); //启用滚轮放大缩小
                //地图、卫星、混合模式切换
                map.addControl(new BMap.MapTypeControl({mapTypes: [BMAP_NORMAL_MAP, BMAP_SATELLITE_MAP, BMAP_HYBRID_MAP]}));
                //向地图中添加缩放控件
                var ctrlNav = new window.BMap.NavigationControl({
                    anchor: BMAP_ANCHOR_TOP_LEFT,
                    type: BMAP_NAVIGATION_CONTROL_LARGE
                });
                map.addControl(ctrlNav);
                //向地图中添加缩略图控件
                var ctrlOve = new window.BMap.OverviewMapControl({
                    anchor: BMAP_ANCHOR_BOTTOM_RIGHT,
                    isOpen: 1
                });
                map.addControl(ctrlOve);
                //向地图中添加比例尺控件
                var ctrlSca = new window.BMap.ScaleControl({
                    anchor: BMAP_ANCHOR_BOTTOM_LEFT
                });
                map.addControl(ctrlSca);

                var point = new Array(); //存放标注点经纬信息的数组
                var marker = new Array(); //存放标注点对象的数组
                var info = new Array(); //存放提示信息窗口对象的数组
                var searchInfoWindow = new Array();//存放检索信息窗口对象的数组
                for (var i = 0; i < markerArr.length; i++) {
                    var p0 = markerArr[i].point.split(",")[0]; //
                    var p1 = markerArr[i].point.split(",")[1]; //按照原数组的point格式将地图点坐标的经纬度分别提出来
                    point[i] = new window.BMap.Point(p0, p1); //循环生成新的地图点
                    marker[i] = new window.BMap.Marker(point[i]); //按照地图点坐标生成标记
                    map.addOverlay(marker[i]);
                    marker[i].setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
                    //显示marker的title，marker多的话可以注释掉
                    var label = new window.BMap.Label(markerArr[i].title, {offset: new window.BMap.Size(20, -10)});
                    marker[i].setLabel(label);
                    // 创建信息窗口对象
                    info[i] = "<p style=font-size:12px;line-height:1.8em;’>" + "</br>" + markerArr[i].details + "</br>地址：" + markerArr[i].address + "</br></p>";
                    //创建百度样式检索信息窗口对象
                    searchInfoWindow[i] = new BMapLib.SearchInfoWindow(map, info[i], {
                        title: markerArr[i].title,      //标题
                        width: 290,             //宽度
                        height: 55,              //高度
                        panel: "panel",         //检索结果面板
                        enableAutoPan: true,     //自动平移
                        searchTypes: [
                            BMAPLIB_TAB_SEARCH,   //周边检索
                            BMAPLIB_TAB_TO_HERE,  //到这里去
                            BMAPLIB_TAB_FROM_HERE //从这里出发
                        ]
                    });
                    //添加点击事件
                    marker[i].addEventListener("click",
                        (function (k) {
                            // js 闭包
                            return function () {
                                //将被点击marker置为中心
                                //map.centerAndZoom(point[k], 18);
                                //在marker上打开检索信息窗口
                                searchInfoWindow[k].open(marker[k]);
                            }
                        })(i)
                    );
                }
            }

            //异步调用百度js
            function map_load() {
                var load = document.createElement("script");
                load.src = "http://api.map.baidu.com/api?v=2.0&ak=0GIA5xcn863ZMkkvrZPQrU9qNQ7B0dE6&callback=map_init";
                document.body.appendChild(load);
            }

            window.onload = map_load;
        </script>
    </fieldset>
</div>
</body>
</html>